CREATE TABLE genres (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    slug        VARCHAR(50)  NOT NULL UNIQUE,
    icon        VARCHAR(10)  NOT NULL,
    color       VARCHAR(7)   NOT NULL DEFAULT '#e8ff00',
    bpm_min     INTEGER      NOT NULL DEFAULT 60,
    bpm_max     INTEGER      NOT NULL DEFAULT 160,
    level       VARCHAR(20)  NOT NULL DEFAULT 'Intermedio',
    time_sig    VARCHAR(10)  NOT NULL DEFAULT '4/4',
    description TEXT,
    subgenres   TEXT         NOT NULL DEFAULT '[]',
    related     TEXT         NOT NULL DEFAULT '[]',
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO genres (name, slug, icon, color, bpm_min, bpm_max, level, time_sig, description, subgenres, related) VALUES
('Rock',    'rock',    '🎸', '#e8ff00', 100, 160, 'Intermedio', '4/4',
 'El rock define generaciones enteras de bateristas. Grooves de 8vos en el hihat con bombo y caja en los tiempos fuertes, fills dramáticos y una presencia física que pocos géneros igualan.',
 '["Classic Rock","Hard Rock","Prog Rock","Punk"]',
 '["Metal","Blues","Pop"]'),

('Funk',    'funk',    '🕺', '#ff6b00', 80, 120, 'Avanzado', '4/4',
 'El funk es el género más exigente para el baterista. Ghost notes, acentos sincopados y el groove que hace mover los pies. Si el público no baila, el baterista no está haciendo funk.',
 '["New Funk","P-Funk","Funk Rock"]',
 '["Soul","Jazz","R&B"]'),

('Jazz',    'jazz',    '🎷', '#4ecdc4', 60, 200, 'Avanzado', '4/4',
 'El jazz exige independencia total de los cuatro miembros. El ride es el corazón del groove, el hihat marca el dos y cuatro, y la caja y el bombo colorean la improvisación del solista.',
 '["Bebop","Cool Jazz","Fusion","Modal Jazz"]',
 '["Blues","Soul","Funk"]'),

('Metal',   'metal',   '🤘', '#8b0000', 140, 220, 'Avanzado', '4/4',
 'El metal lleva la técnica del baterista al extremo. Doble bombo, blast beats, polirritmos y velocidades que desafían los límites físicos. La precisión es todo.',
 '["Thrash","Death Metal","Djent","Progressive Metal"]',
 '["Rock","Punk"]'),

('Latin',   'latin',   '💃', '#ff0080', 80, 140, 'Avanzado', '4/4',
 'La percusión latina tiene raíces profundas en ritmos africanos y españoles. Clave, conga y timbales se traducen a la batería con una riqueza rítmica única.',
 '["Salsa","Bossa Nova","Cumbia","Afrobeat"]',
 '["Bossa","Soul"]'),

('Reggae',  'reggae',  '🌴', '#00aa44', 60, 90, 'Básico', '4/4',
 'El reggae pone la caja en el tres, el bombo en el uno y el cuatro, y el hihat en las corcheas. Simple en apariencia, difícil de hacer sonar bien. El feel es todo.',
 '["Roots Reggae","Dub","Dancehall","Ska"]',
 '["Blues","Soul"]'),

('Blues',   'blues',   '🎺', '#1e3a8a', 60, 120, 'Básico', '4/4',
 'El blues es la raíz de casi toda la música popular occidental. El shuffle de blues, con su feel de corcheas de tresillos, es el primer groove que todo baterista debe dominar.',
 '["Chicago Blues","Delta Blues","Blues Rock"]',
 '["Rock","Jazz","Soul"]'),

('Pop',     'pop',     '🎵', '#ff69b4', 90, 130, 'Básico', '4/4',
 'El pop moderno exige precisión, sobriedad y servicio a la canción. El baterista de pop toca lo que la canción necesita, no lo que quiere mostrar.',
 '["Indie Pop","Electropop","Dream Pop"]',
 '["Rock","Soul","R&B"]'),

('Soul',    'soul',    '✨', '#9333ea', 70, 110, 'Intermedio', '4/4',
 'El soul combina el peso del gospel con el groove del R&B. La caja suena con convicción, el hihat es fluido y el bolsillo rítmico es profundo.',
 '["Southern Soul","Neo Soul","Gospel"]',
 '["Funk","R&B","Jazz"]'),

('R&B',     'r-and-b', '🎤', '#dc2626', 70, 110, 'Intermedio', '4/4',
 'El R&B contemporáneo fusiona electrónica con instrumentación en vivo. El baterista debe convivir con loops, click tracks y producción densa.',
 '["Contemporary R&B","New Jack Swing"]',
 '["Soul","Hip-Hop","Funk"]'),

('Hip-Hop', 'hip-hop', '🎧', '#171717', 70, 110, 'Intermedio', '4/4',
 'El hip-hop nació de los breaks — los fragmentos de batería más groovy de los discos de funk y soul. Hoy el baterista en vivo recrea esos patrones con swing y precisión.',
 '["Boom Bap","Trap","Lo-Fi"]',
 '["R&B","Funk","Soul"]'),

('Bossa',   'bossa',   '🌊', '#0ea5e9', 60, 100, 'Avanzado', '3/4',
 'La bossa nova exige delicadeza extrema. El patrón de palo en el aro de la caja que imita el pandeiro, combinado con el bombo sincopado, crea un groove único e inconfundible.',
 '["Bossa Nova","Samba","MPB"]',
 '["Latin","Jazz","Soul"]');
