CREATE TABLE grooves (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(150) NOT NULL UNIQUE,
    title       VARCHAR(100) NOT NULL,
    author_id   BIGINT       NOT NULL REFERENCES users(id),
    genre_id    BIGINT       NOT NULL REFERENCES genres(id),
    bpm         INTEGER      NOT NULL,
    level       VARCHAR(20)  NOT NULL,
    likes       BIGINT       NOT NULL DEFAULT 0,
    plays       BIGINT       NOT NULL DEFAULT 0,
    featured    BOOLEAN      NOT NULL DEFAULT FALSE,
    tags        TEXT         NOT NULL DEFAULT '[]',
    description TEXT,
    pattern     TEXT         NOT NULL DEFAULT '{}',
    time_sig    VARCHAR(10)  NOT NULL DEFAULT '4/4',
    bars        INTEGER      NOT NULL DEFAULT 1,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, username, name, email, password_hash, bio, avatar_seed, color, init, plan)
VALUES
(100, 'bernardp',    'Bernard Purdie',    'bernard@drumhub.com', '$2a$10$slYQmyNdgTY18LGvgxPwHOIL4LTQZ7A83gdvGn1FPJ3U9qQ2jAOiK', 'The Funky Drummer', 'purdie',  '#ff6b00', 'B', 'FREE'),
(101, 'jazzcat',     'John Bonham',       'bonham@drumhub.com',  '$2a$10$slYQmyNdgTY18LGvgxPwHOIL4LTQZ7A83gdvGn1FPJ3U9qQ2jAOiK', 'Led Zeppelin',      'bonham',  '#e8ff00', 'J', 'FREE'),
(102, 'funkybones',  'Clyde Stubblefield','clyde@drumhub.com',   '$2a$10$slYQmyNdgTY18LGvgxPwHOIL4LTQZ7A83gdvGn1FPJ3U9qQ2jAOiK', 'The Funky Drummer', 'cobham',  '#4ecdc4', 'C', 'PRO'),
(103, 'groovemaster','Steve Gadd',        'gadd@drumhub.com',    '$2a$10$slYQmyNdgTY18LGvgxPwHOIL4LTQZ7A83gdvGn1FPJ3U9qQ2jAOiK', 'Session legend',    'gadd',    '#9333ea', 'S', 'PRO');

INSERT INTO grooves (slug, title, author_id, genre_id, bpm, level, likes, plays, featured, tags, description, pattern, time_sig, bars)
VALUES
(
  'purdie-shuffle',
  'Purdie Shuffle',
  100,
  (SELECT id FROM genres WHERE slug = 'funk'),
  98, 'Avanzado', 487, 3120, TRUE,
  '["shuffle","ghost notes","independencia","steely dan"]',
  'El groove que definió el funk moderno. Ghost notes en la caja, hihat sincopado y un bombo que conversa con el bajo.',
  '{"china":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"crash":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"splash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride_bell":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"hihat":[1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1],"hihat_open":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"snare":[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],"tom1":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom2":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom3":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"kick":[1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0]}',
  '4/4', 1
),
(
  'bonham-levee',
  'Bonham Levee Break',
  101,
  (SELECT id FROM genres WHERE slug = 'rock'),
  76, 'Avanzado', 892, 5400, FALSE,
  '["rock","led zeppelin","triplets","feel"]',
  'El groove más copiado de la historia del rock. Bonham usaba palos 2B y tocaba con una fuerza descomunal.',
  '{"china":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"crash":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"splash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride_bell":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"hihat":[1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0],"hihat_open":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"snare":[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],"tom1":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom2":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom3":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"kick":[1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0]}',
  '4/4', 1
),
(
  'funky-drummer',
  'Funky Drummer',
  102,
  (SELECT id FROM genres WHERE slug = 'funk'),
  97, 'Avanzado', 654, 4100, FALSE,
  '["funk","clyde","james brown","16ths"]',
  'El break más sampleado de la historia. Clyde Stubblefield crea un groove imposible de ignorar.',
  '{"china":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"crash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"splash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride_bell":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"hihat":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"hihat_open":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"snare":[0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0],"tom1":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom2":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom3":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"kick":[1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0]}',
  '4/4', 1
),
(
  'jazz-ride',
  'Jazz Ride Standard',
  103,
  (SELECT id FROM genres WHERE slug = 'jazz'),
  140, 'Avanzado', 312, 2200, FALSE,
  '["jazz","ride","swing","bebop"]',
  'El patrón de ride de swing estándar. La base del jazz moderno: ride en tresillos, hihat en 2 y 4, bombo y caja como coloristas.',
  '{"china":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"crash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"splash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride":[1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1],"ride_bell":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"hihat":[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],"hihat_open":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"snare":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom1":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom2":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom3":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"kick":[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]}',
  '4/4', 1
),
(
  'half-time-shuffle',
  'Half Time Shuffle',
  103,
  (SELECT id FROM genres WHERE slug = 'rock'),
  96, 'Avanzado', 445, 2900, FALSE,
  '["shuffle","half time","toto","rosanna"]',
  'El groove de Rosanna de Toto. Jeff Porcaro lo inventó combinando dos patrones distintos. Es técnicamente demandante.',
  '{"china":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"crash":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"splash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride_bell":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"hihat":[1,1,0,1,1,0,1,0,1,1,0,1,1,0,1,0],"hihat_open":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"snare":[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],"tom1":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom2":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom3":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"kick":[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]}',
  '4/4', 1
),
(
  'reggae-one-drop',
  'Reggae One Drop',
  101,
  (SELECT id FROM genres WHERE slug = 'reggae'),
  75, 'Básico', 178, 1100, FALSE,
  '["reggae","one drop","roots","basic"]',
  'El one drop clásico del reggae. La caja en el tres, el bombo ausente en el uno. Simple pero profundo.',
  '{"china":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"crash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"splash":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ride_bell":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"hihat":[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],"hihat_open":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"snare":[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],"tom1":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom2":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"tom3":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"kick":[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0]}',
  '4/4', 1
);
