CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id    BIGINT       NOT NULL REFERENCES users(id),
    type            VARCHAR(20)  NOT NULL,
    triggered_by    VARCHAR(50)  NOT NULL,
    read            BOOLEAN      NOT NULL DEFAULT FALSE,
    groove_slug     VARCHAR(150),
    groove_title    VARCHAR(100),
    snippet         VARCHAR(300),
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, read, created_at DESC);
